### ISSUE TITLE
2015 version

### ISSUE THREAD

**Issue by davikawasaki** [warren-bank/gyp_msvs_version_2012e#1]
Do you intend to release a msvs version 2015e? Node v6.x+ require the 2015 build tools. This portable version is going to truly help me in my company.

**Comment by warren-bank** [comment]
Hi. Yeah, this monstrosity is crazy old. It comes from a time when Microsoft was still behaving as though open-source is their mortal enemy (if only that were true).

Since then, they've relaxed that position; I hope.. considering they now own github. Have you tried their official [build tools](https://www.npmjs.com/package/windows-build-tools) for node?

If I had the need, I'd probably make another portable bundle. But that first one took days to get (mostly) working, and I just don't have a good reason to tackle that beast yet again. I'm sure the official tools are just a wrapper around non-portable installers.. which is less than ideal. But, the simplest portable solution is probably just to virtualize a build environment in VirtualBox. It would eat up a fair bit of hard disk, and it would require starting the VM to run a build.. but the generated binaries should run outside of the VM, and it wouldn't change the bare-metal OS in any way.

Sorry it's not the answer you wanted..

**Comment by davikawasaki** [comment]
Hey, thanks for the answer. I'll try to run a VM or even try to do the same as you did. In my company we kinda don't have admin access, so I'm doing everything I can with portable versions. At least I want to thank you for giving me a direction. Cheers!
